### ISSUE TITLE
About the file structure.

### ISSUE THREAD

**Issue by JinyaoZhu** [FLYing-maniPULATOR/flypulator#1]
Hi Leute, just a little question.

Why we using the current structure:

flypulator
├── flypulator_common_msgs
├── flypulator_control
├── flypulator_description
├── flypulator_simulation
│   ├── flypulator_plugin_aero
│   ├── flypulator_plugin_control
│   ├── flypulator_simulation
│   └── flypulator_simulation_gazebo
├── flypulator_teleoperation
├── flypulator_traj_generator
└── README.md

instead of:

flypulator
├── flypulator_common_msgs
├── flypulator_control
├── flypulator_description
├── flypulator_plugin_gazebo (with areo_plugin.cc and control_plugin.cc inside)
├── flypulator_simulation_gazebo
├── flypulator_teleoperation
├── flypulator_traj_generator
├── flypulator (meta package)
└── README.md

It seems those packages in flypulator_simulation are parallel to other packages.
Or am I thinking wrong?

**Comment by chaolmu** [comment]
we use this structure to express not only in ros mechnismus, but also in real folder structure, that flypulator_simulation is a metapackage with plugin package and launch package as subpackages.
As you suggested the flat structure above, I am think about that we create a central package for all launch files and rename flypulator_plugin_aero und control as flypulator_gazebo_sim.
flypulator
├── flypulator_common_msgs
├── flypulator_control
├── flypulator_description
├── flypulator_gazebo_sim (with areo_plugin.cc and control_plugin.cc inside)
├── flypulator_teleoperation
├── flypulator_traj_generator
├── flypulator (meta package)
└── README.md

**Comment by JinyaoZhu** [comment]
@chaolmu Yes, I think it would be good, as the structure you proposed. Exactly, the former folder flypulator_simulation_gazebo contains only some launch files.
