### ISSUE TITLE
Gazebo model does not spawn

### ISSUE THREAD

**Issue by danneboom** [FLYing-maniPULATOR/flypulator#10]
I pulled master branch, performed catkin_make and launched gazebo.launch. Gazebo starts, but the model is not loaded:

[ WARN] [1527064228.945859305]: The root link base_link has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
[gazebo-2] process has died [pid 8028, exit code 255, cmd /opt/ros/kinetic/lib/gazebo_ros/gzserver -e ode worlds/empty.world __name:=gazebo __log:=/home/jan/.ros/log/8c3155b4-5e63-11e8-9a9a-dc5360d946bc/gazebo-2.log].
log file: /home/jan/.ros/log/8c3155b4-5e63-11e8-9a9a-dc5360d946bc/gazebo-2*.log
SpawnModel script started
[INFO] [1527064229.725548, 0.000000]: Loading model XML from file
[INFO] [1527064229.725953, 0.000000]: Waiting for service /gazebo/spawn_urdf_model

@chaolmu I can show you this later

**Comment by chaolmu** [comment]
roll back to  old model, new model is still under development.  And keep in mind: old model has bugs, only thrust and torque are applied correctly, other wrench (which are small, e.g. roll moment, hub force) are possiblly applied to wrong direction.

**Comment by danneboom** [comment]
Fixed in current commit in sim-devel. merged soon.
