### ISSUE TITLE
Error in aerodynamics

### ISSUE THREAD

**Issue by danneboom** [FLYing-maniPULATOR/flypulator#13]
There seems to be a major mistake in aerodynamic calculation. The rotors 1,2,5 are similar and the rotors 3,4,6, but I dont see any reason why the thrust of some rotors is 3-5 times higher. And the torque is also weird..
The values in the legend are the proportional factors k resp. b, which should be equal for all motors since they have no differences..

![force](https://user-images.githubusercontent.com/20741239/40471883-44200d4e-5f38-11e8-984b-57cc79ade999.png)

![torque](https://user-images.githubusercontent.com/20741239/40471884-445deace-5f38-11e8-90a4-1d3af9f8ecd2.png)

**Comment by chaolmu** [comment]
I am on the way. I will review the issue later when possible.

**Comment by JinyaoZhu** [comment]
@danneboom I have detected a sign mistake of motor 1 in aero_plugin and updated the sim-dev branch. I recorded data in aero_plugin and got these two images, I don't know if it fits the theory:
![force](https://user-images.githubusercontent.com/7758185/40488253-9ccf9774-5f66-11e8-8abd-ac428c7fe18e.png)
![torque](https://user-images.githubusercontent.com/7758185/40488264-a338ec82-5f66-11e8-83e8-46ee679c580d.png)

**Comment by danneboom** [comment]
Can you please give me a short update what works and what doesnt work at the moment?

**Comment by JinyaoZhu** [comment]
@danneboom sorry for the late update. Now the sim-devel is runnable. Now I added a simplified esc+motor model approximated as a PT1-Glied and approximated ground effect(not concerning the tilting angle) of the thrust of all motors, both according to the ifacconf-paper. The parameter of the  PT1-Glied is still not fine-tuned, and it has now a gain of ~0.9 and a time constant of ~45ms.
And the controller_plugin is now a standalone part(I may still need it for testing the propulsion_plugin), it just publishing rotor_cmd to propulsion_plugin, the propulsion_plugin receive rotor_cmd and generate force and moment in gazebo, when you want to use your controller you can just disable the plugin in the .urdf file. And if you want to check the force and torque of each motor you can subscribe to the "/drone/blade_x_wrench" topic.
The fake_sensor_plugin is now publishing the drone real states in the gazebo world at 1000Hz. You can subscribe the topic "/drone/real_state" with UavStateStamped msg type. These drone states is now not sychronized with the gazebo world, so it may have a small delay. I dont know if it causes problem. If it doese maybe I should fine a better solution later.
For the aerodynamic parameters, the code seems differt from the formula in Ge's SA, he calculated T first and then used the T euqation to get C_T. The motor moments is still not "proportion" to omega^2. It seems we need to dig deeper. But now, the direction of the force and torque should be right(at least in z direction).

**Comment by JinyaoZhu** [comment]
I have found mistake in calculation of induced airflow velocity Vi and general dimensionless induced velocity lambda and get these figures:
![force](https://user-images.githubusercontent.com/7758185/40586902-b03a9782-61c8-11e8-89f5-b1336bb13995.png)
![torque](https://user-images.githubusercontent.com/7758185/40586903-b2a2155e-61c8-11e8-85f2-0bf910738a2d.png)

**Comment by JinyaoZhu** [comment]
I also change the equations according to Hiller's Beleg, now the rotor vel should higher than 350, or it will get a negative C_T and negative moment.

**Comment by danneboom** [comment]
I will have a look tomorrow. I dont understand the meaning of lambda by now, and how it needs to be calculated..

**Comment by chaolmu** [comment]
the calculation in code is obviously not according to  formula introduced in SA (at least the sequence). I am working on rewriting the code clearly.

**Comment by danneboom** [comment]
I am writing the rotor aerodynamics into a for-loop, committing soon...

**Comment by danneboom** [comment]
Done.

**Comment by danneboom** [comment]
@JinyaoZhu can you please check the torque curve again?

@all Open Questions: 
- Where is the value of CD0 taken from? Cant find in Hiller thesis.
- In function setForce and setTorque are the rotor forces and torques applied to model. I think here a transform to body frame is needed before applying.

**Comment by JinyaoZhu** [comment]
@danneboom torque curve with "for loop" version, I write the test data into a .csv file in propulsion_plugin(it has a bool WRITE_CSV_FILE, and you have to change the output path), and plot with a python script:
![torque](https://user-images.githubusercontent.com/7758185/40609671-a5653c66-626f-11e8-8b4d-6845d5c6324b.png)

**Comment by danneboom** [comment]
Thank you very much. I will try a linear curve fit..

**Comment by chaolmu** [comment]
@JinyaoZhu have you ever changed the calculation of V_i in the plugin? Qiang's implementation is obviously wrong. 
V_i1 = -v_c/2 + sqrt((v_c/2)^2 + v_i,h^2)
V_i must be always bigger than zero for normal working state, but in the SA page 48 figure 7.3, the curve is always bellow zero.
I am also not sure that all aeroparameters are valid to use, especially theta_0 and thetha_tw. I do not understand what are they, but 0.7 and 0.5 are not good value. Could you figure out theirs definition and update all parameters w.r.t. our 15" propeller.

**Comment by JinyaoZhu** [comment]
@chaolmu Yes, we've corrected the V_i according to  Hiller's Beleg.

**Comment by danneboom** [comment]
Seems like the aerodynamic is okay now! I generated rotor characeristics by setting the rotor velocity from -1000 to 1000 in 1-steps and set the airflow (v_wind - v_drone) manually to 0, 1 and -1. The curves look basically okay, but I think we have to fix the discontinuity for v=0 (v getting smaller). I will try to implement the bezier spline from Hillers thesis.
I will commit my code to an additional branch.

The third and last plot are f_z resp. tau_z (sorry for wrong axis label)

![f_x](https://user-images.githubusercontent.com/20741239/40709362-1d9b706a-63f6-11e8-92a7-e26bd1f2cebd.png)
![f_y](https://user-images.githubusercontent.com/20741239/40709363-1db9c06a-63f6-11e8-9633-4e8d72522f83.png)
![f_z](https://user-images.githubusercontent.com/20741239/40709364-1dd5b716-63f6-11e8-9491-23772af32c02.png)



![tau_x](https://user-images.githubusercontent.com/20741239/40709367-1e5586b2-63f6-11e8-8e02-b2972bd8430f.png)
![tau_y](https://user-images.githubusercontent.com/20741239/40709369-1e74b578-63f6-11e8-87f4-8f2bd0a80133.png)
![tau_z](https://user-images.githubusercontent.com/20741239/40709370-1e92595c-63f6-11e8-9dda-935f07977e7b.png)

**Comment by danneboom** [comment]
Hiller takes following values for theta_0 and theta_tw (page 50 / (61/94)):
theta_ 0 = 38° = 0.663 rad
theta_tw = 8° = 0,140 rad

**Comment by danneboom** [comment]
The controller basically works with this aerodynamics now without motor dynamics. So I will not implement Bezier spline at the moment.

**Comment by chaolmu** [comment]
The aerodynamic model will be investigated theoretically and experimentally. The simple model with constant k and b should be used until new model is validated. This is a future feature.
