### ISSUE TITLE
FakeSensorPlugin Publish Rate

### ISSUE THREAD

**Issue by danneboom** [FLYing-maniPULATOR/flypulator#16]
Where can the publish rate be reduced? I tried changing the timeout variable in QueueThread(), e.g. to 1, but it doesnt change anything, the states are still published incredibly often.

Additionally, the acceleration values are very high when the drone doesnt move, between 0 and 10 m/s². Maybe this is a gazebo thing and how acceleration is calculated.. but actually it must provide better values here. There is no force with could cause such a high acceleration at a rotor speed of 0.01, and I dont think that gazebo calculates the acceleration by numerical derivation of velocity..

**Comment by JinyaoZhu** [comment]
I've added a simple divider to the states publisher, and it should now have a publishing rate of 250Hz.

**Comment by danneboom** [comment]
Great, thanks. Do you know why the acceleration values are such wrong?

**Comment by danneboom** [comment]
and could you please commit you python script?

**Comment by JinyaoZhu** [comment]
I've uploaded the script. And have no idea why the acceleration will such weird.

**Comment by danneboom** [comment]
Thank you. Maybe we have to use a IMU Sensor plugin..

**Comment by danneboom** [comment]
Thats really weird. Even if I dont apply any force/torque, the linear and angular acceleration jumps between +-20. 
There is still a IMU sensor from hector library in urdf file, but its not publishing to the topic specified at <topicName>. Same for you?

**Comment by danneboom** [comment]
Actually the controller does not need the acceleration.. so this can be solved later.
