### ISSUE TITLE
COM, Mass, Inertia of drone

### ISSUE THREAD

**Issue by danneboom** [FLYing-maniPULATOR/flypulator#18]
Is the base link of the urdf file really equal to the Center of Mass? 
What is the total mass and inertia w.r.t. the center of mass?

**Comment by chaolmu** [comment]
You can observe the frame definitions with roslaunch flypulator_description display.launch.The origin of base_link is at center of lower surface of the lower round central disk, where is obviously not COM. Any requirement from your side? I can redefine the base_link at geometric center, the COM can also be know in Solidworks.

**Comment by danneboom** [comment]
Well, the body frame is defined to origin in the COM. The controller needs to know the position, velocity and acceleration of the COM as well as the inertia w.r.t. the COM, since the equations of motion used by the controller to calculate control force and torque are w.r.t. COM. And the assumption that the inertia matrix is a diagonal matrix is only valid if being w.r.t. COM. So yes, I think we need a body frame in the center of mass, and should define all states messages w.r.t. this body frame.

**Comment by danneboom** [comment]
Ok, so we take the values m = 6,15kg and I = diag(0.454,0.328,0.699) ?

**Comment by danneboom** [comment]
The output of propulsion plugin, 
m = this->link0->GetInertial()->GetMass();
is 5.77 kg.. why 400g missing?

**Comment by chaolmu** [comment]
@danneboom the sum of all links's mass in URDF is exactly 6.15359, I don't know what is returned by calling GetMass().

**Comment by chaolmu** [comment]
The sum of all the links' mass is the total mass. this->link0->GetInertial()->GetMass() is only the mass of base_link
