### ISSUE TITLE
Drone moves even if no wrench applied

### ISSUE THREAD

**Issue by danneboom** [FLYing-maniPULATOR/flypulator#19]
Setting the boolean add_wrench_to_drone to false still causes a movement if the rotor cmd is around 200 or higher. It definitely comes from SetVelocity() method, which seems to cause forces/torques as well. I thought actually SetVelocity() should only cause propeller movement but without adding forces/torques to the drone. What do you think?

**Comment by JinyaoZhu** [comment]
The model has no movement, only if I set no wrench and zero velocity, don't know why setVelocity() causes movement of the model.

**Comment by danneboom** [comment]
Does the propeller have an inertia in urdf? Maybe the velocity change of the propeller cause a torque if the propeller have an inertia.

**Comment by danneboom** [comment]
I think the inertia of the propeller blades is too high: 
 <inertia
        ixx="7.9927E-06"
        ixy="2.4595E-05"
        ixz="5.8974E-10"
        iyy="0.0014004"
        iyz="1.7645E-10"
        izz="0.0014072" />

@chaolmu where are these values from? Hillers values e.g. are 10 times lower (page 51, table 7.6)

**Comment by chaolmu** [comment]
@danneboom the parameters comes from solidworks, the material is undefined and maybe default value is  some kind of metal. You can change it to a reasonable value by hand. I will define the material later.

**Comment by chaolmu** [comment]
Since the integration of new TAROT drone model is finished and will replace the igs hexarotor, this issue is closed.
