### ISSUE TITLE
Build error in aero and control plugin, CMakeLists.txt missing

### ISSUE THREAD

**Issue by danneboom** [FLYing-maniPULATOR/flypulator#2]
/home/jan/flypulator_ws/src/flypulator/flypulator_simulation/flypulator_plugin_aero

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:63 (catkin_workspace)

-- +++ processing catkin package: 'flypulator_plugin_control'
-- ==> add_subdirectory(flypulator/flypulator_simulation/flypulator_plugin_control)
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkin_workspace.cmake:116 (add_subdirectory):
  The source directory

    /home/jan/flypulator_ws/src/flypulator/flypulator_simulation/flypulator_plugin_control

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:63 (catkin_workspace)

-- Configuring incomplete, errors occurred!

On both branches, master and crtl-devel

**Comment by danneboom** [comment]
Possible reason: CMakeLists.txt is in .gitignore?! Seems to affect all directories

**Comment by chaolmu** [comment]
Yes, my fault. I want just to ignore the CMakeLists link in /src. I will fix it

**Comment by danneboom** [comment]
Ah okay, I just fixed it

**Comment by danneboom** [comment]
Please commit your CMakeLists

**Comment by chaolmu** [comment]
sorry for late commit because of meeting. It's done
