### ISSUE TITLE
Motor dynamic does not work bidirectional

### ISSUE THREAD

**Issue by danneboom** [FLYing-maniPULATOR/flypulator#20]
Negative rotor commands are not processed correctly, probably the reason that the sign is taken in OnControlMsg, but it should be processed after motor dynamics as you pointed out in comment in line 489.
//TODO: di_vel and di_force should change after motor dynamic, not here
The rotor commands in figure were 
- 100,-100 at ~5s
- 200, 100 at ~14.5s
- -200, 100 at ~22s

(for manual rotor command use e.g.
`rostopic pub /drone/rotor_cmd flypulator_common_msgs/RotorVelStamped '{header: auto, velocity: [-200,100,0,0,0,0]}' `)

![figure_1](https://user-images.githubusercontent.com/20741239/40772546-89b859fa-64c0-11e8-9b0c-83ea58257ed3.png)

**Comment by JinyaoZhu** [comment]
I fixed the bug and commited, you can test it again.
![motor](https://user-images.githubusercontent.com/7758185/40801869-53ab2424-6514-11e8-9867-2db950a2f770.png)
