### ISSUE TITLE
Gazebo Error when launching new model

### ISSUE THREAD

**Issue by chaolmu** [FLYing-maniPULATOR/flypulator#22]
Hallo,
in the branch Hexatilt I am trying to launch gazebo with new model but get following error:

SpawnModel script started
[INFO] [1529791339.078847, 0.000000]: Loading model XML from ros parameter
[INFO] [1529791339.085809, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
[ INFO] [1529791339.312542911, 0.023000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1529791339.354254153, 0.063000000]: Physics dynamic reconfigure ready.
[INFO] [1529791339.391729, 0.095000]: Calling service /gazebo/spawn_urdf_model
[rospack] Error: package 'hexatilt_description' not found
[librospack]: error while executing command
[FATAL] [1529791339.433326100, 0.134000000]: Package[hexatilt_description] does not have a path
Service call failed: service [/gazebo/spawn_urdf_model] responded with an error: 
[ INFO] [1529791339.545312551, 0.247000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1529791339.646113364, 0.335000000]: Physics dynamic reconfigure ready.
[urdf_spawner-4] process has finished cleanly
log file: /home/chao/.ros/log/180501d6-7731-11e8-afd6-34f39a461fb8/urdf_spawner-4*.log
Segmentation fault
[gazebo_gui-3] process has died [pid 11339, exit code 139, cmd /opt/ros/kinetic/lib/gazebo_ros/gzclient __name:=gazebo_gui __log:=/home/chao/.ros/log/180501d6-7731-11e8-afd6-34f39a461fb8/gazebo_gui-3.log].
log file: /home/chao/.ros/log/180501d6-7731-11e8-afd6-34f39a461fb8/gazebo_gui-3*.log

Any idea?

**Comment by einarGit** [comment]
Yup. I know what the problem is. Pushing solution tomorrow.

Den søn. 24. jun. 2018, 00.06 skrev Chao Yao <notifications@github.com>:

**Comment by chaolmu** [comment]
I have fixed it. The package name were not updated to flypulator_description_new in some files.
