### ISSUE TITLE
Rotor Cmd Message

### ISSUE THREAD

**Issue by danneboom** [FLYing-maniPULATOR/flypulator#3]
According to issue from former repo, we should define a message for rotor commands. 

(file-)name: RotorCommand.msg? RotorVelocityCommand.msg?

content: - six floats? Or an array of floats to be independent from number of rotors?
              - Header required?

What do you think?

**Comment by chaolmu** [comment]
I advise RotorVelCmd.msg for short.
It is better to be universal without limitation of rotor number.
Use the same header as twist command? At least time stamp should be included.

**Comment by chaolmu** [comment]
I have defined a msg named RotorVelStamped for your use. Adaptation in gazebo plugin will be carried soon.

**Comment by chaolmu** [comment]
It is usd to store corresponding joint names. I followed the style of sensor_msg/joint_state.

**Comment by danneboom** [comment]
I used the message but dont know exactly what i have to add in 
string[] name. 
Currently I use "blade_joint1" .. "blade_joint6", @JinyaoZhu @chaolmu please tell me if the string must be different.

**Comment by chaolmu** [comment]
you can find the name e.g. in Load() in aero_plugin.cc, or in .urdf
They are blade_joint1 to blade_joint6
Not the name but the size of velocity[] is checked so far to receive rotor_cmd.
