### ISSUE TITLE
UAV Parameters

### ISSUE THREAD

**Issue by danneboom** [FLYing-maniPULATOR/flypulator#4]
I tried to extract the geometric parameters like size of the uav, mass, inertia and so on from the .urdf file. Maybe the .urdf file needs to be reviewed, as e.g. the mass is greater than 10 kg (!) (base_link)

- The distance from COM to each rotor seems to be around 0.5m, a little higher (0.53m?) Is there a reason why such values have been chosen?

- Which values should I take for thrust ratio k (f = k omega^2) and for drag ratio b (torque = b omega^2)

**Comment by chaolmu** [comment]
May be it is better and cleaner to find a Hexarotor mode onlinel, modify the tilted angle and transfer to urdf. Then add gazebo plugin in urdf. It just has to have same link and joint name.
@JinyaoZhu could you do this task as soon as possible? My time is very limited.

**Comment by JinyaoZhu** [comment]
@chaolmu Yes, I think I can do this.

**Comment by JinyaoZhu** [comment]
@chaolmu I have found a drone model name "neo11", and change the angle, and the name. But it seems has no blade link and joint, the blades are “secured” with the motor. Can we use this model?
You can type "roslaunch flypulator_description neo11.launch" to check the model.

**Comment by danneboom** [comment]
@chaolmu But I still need the factors k and b, I dont know how to obtain them from the complex aerodynamic equations.. maybe it is possible to output the z-forces calculated in aero_plugin.cc and the corresponding rotor velocities and estimate a proportional factor. Is anyone inside the aero_plugin.cc and able to do this efficiently? Or any other ideas?

**Comment by chaolmu** [comment]
I have purchased a 3d model of our new UAV, in the next step I will modify it and transfer it to urdf to update flypulator_description

**Comment by chaolmu** [comment]
@danneboom What do you think would be a good tilted angle? In my opinion 15~30 degree? I want do tilting directly in CAD.

**Comment by danneboom** [comment]
@chaolmu 13.6° is from a optimization of Rajappa et al., forgot to explain that in my thesis.

**Comment by chaolmu** [comment]
@danneboom I advise to theoretically estimat the coefficient with formulars in Mr. Ge's SA. The estimate assumption will be hovering state, so the induced velocity is always v_i,h. V_xy = 0.
It leads:
lambda = v_ih/(omega*R) (3.25)
sigma = (N_E*c)/(pi*R) (3.28)
mu = 0 (3.34)
Then you can calculate with (3.35) (3.36)
