### ISSUE TITLE
Build error in control_plugin.cc

### ISSUE THREAD

**Issue by danneboom** [FLYing-maniPULATOR/flypulator#5]
After delete /build and /devel folder (master branch):
Seems like the message are generated after compiling control_plugin.cc 
Second run of catkin_make succeeded. 

/home/jan/flypulator_ws/src/flypulator/flypulator_gazebo_plugin/src/control_plugin.cc:817:30: error: ‘flypulator_common_msgs’ does not name a type
     void OnRosRatioMsg(const flypulator_common_msgs::Vector6dMsgConstPtr &_thrust_moment_ratio)
                              ^
/home/jan/flypulator_ws/src/flypulator/flypulator_gazebo_plugin/src/control_plugin.cc:817:74: error: expected unqualified-id before ‘&’ token
     void OnRosRatioMsg(const flypulator_common_msgs::Vector6dMsgConstPtr &_thrust_moment_ratio)
                                                                          ^
/home/jan/flypulator_ws/src/flypulator/flypulator_gazebo_plugin/src/control_plugin.cc:817:74: error: expected ‘)’ before ‘&’ token
/home/jan/flypulator_ws/src/flypulator/flypulator_gazebo_plugin/src/control_plugin.cc:817:74: error: expected ‘;’ at end of member declaration
/home/jan/flypulator_ws/src/flypulator/flypulator_gazebo_plugin/src/control_plugin.cc:817:75: error: ‘_thrust_moment_ratio’ does not name a type
     void OnRosRatioMsg(const flypulator_common_msgs::Vector6dMsgConstPtr &_thrust_moment_ratio)
                                                                           ^
/home/jan/flypulator_ws/src/flypulator/flypulator_gazebo_plugin/src/control_plugin.cc: In member function ‘virtual void gazebo::ControlPlugin::Load(gazebo::physics::ModelPtr, sdf::Eleme
ntPtr)’:
/home/jan/flypulator_ws/src/flypulator/flypulator_gazebo_plugin/src/control_plugin.cc:194:50: error: ‘flypulator_common_msgs’ was not declared in this scope
         this->pub_cmd = this->rosNode->advertise<flypulator_common_msgs::Vector6dMsg>("/drone/rotor_cmd", 100);
                                                  ^
/home/jan/flypulator_ws/src/flypulator/flypulator_gazebo_plugin/src/control_plugin.cc:194:40: error: parse error in template argument list
         this->pub_cmd = this->rosNode->advertise<flypulator_common_msgs::Vector6dMsg>("/drone/rotor_cmd", 100);
                                        ^
/home/jan/flypulator_ws/src/flypulator/flypulator_gazebo_plugin/src/control_plugin.cc:194:110: error: no matching function for call to ‘ros::NodeHandle::advertise(const char [17], int)’
         this->pub_cmd = this->rosNode->advertise<flypulator_common_msgs::Vector6dMsg>("/drone/rotor_cmd", 100);

/home/jan/flypulator_ws/src/flypulator/flypulator_gazebo_plugin/src/control_plugin.cc:194:40: error: parse error in template argument list
         this->pub_cmd = this->rosNode->advertise<flypulator_common_msgs::Vector6dMsg>("/drone/rotor_cmd", 100);
                                        ^
/home/jan/flypulator_ws/src/flypulator/flypulator_gazebo_plugin/src/control_plugin.cc:194:110: error: no matching function for call to ‘ros::NodeHandle::advertise(const char [17], int)’
         this->pub_cmd = this->rosNode->advertise<flypulator_common_msgs::Vector6dMsg>("/drone/rotor_cmd", 100);
                                                                                                              ^
In file included from /opt/ros/kinetic/include/ros/ros.h:45:0,
                 from /home/jan/flypulator_ws/src/flypulator/flypulator_gazebo_plugin/src/control_plugin.cc:21:
/opt/ros/kinetic/include/ros/node_handle.h:249:15: note: candidate: template<class M> ros::Publisher ros::NodeHandle::advertise(const string&, uint32_t, bool)
     Publisher advertise(const std::string& topic, uint32_t queue_size, bool latch = false)
               ^
/opt/ros/kinetic/include/ros/node_handle.h:249:15: note:   template argument deduction/substitution failed:
/home/jan/flypulator_ws/src/flypulator/flypulator_gazebo_plugin/src/control_plugin.cc:194:110: error: template argument 1 is invalid
         this->pub_cmd = this->rosNode->advertise<flypulator_common_msgs::Vector6dMsg>("/drone/rotor_cmd", 100);

In file included from /opt/ros/kinetic/include/ros/node_handle.h:42:0,
                 from /opt/ros/kinetic/include/ros/ros.h:45,
                 from /home/jan/flypulator_ws/src/flypulator/flypulator_gazebo_plugin/src/control_plugin.cc:21:
/opt/ros/kinetic/include/ros/subscribe_options.h:154:27: note: candidate: template<class M> static ros::SubscribeOptions ros::SubscribeOptions::create(const string&, uint32_t, const boo
st::function<void(const boost::shared_ptr<const T>&)>&, const VoidConstPtr&, ros::CallbackQueueInterface*)
   static SubscribeOptions create(const std::string& topic, uint32_t queue_size,
                           ^
/opt/ros/kinetic/include/ros/subscribe_options.h:154:27: note:   template argument deduction/substitution failed:
/home/jan/flypulator_ws/src/flypulator/flypulator_gazebo_plugin/src/control_plugin.cc: In member function ‘void gazebo::ControlPlugin::OnlinkMsg(const LinkStatesConstPtr&)’:
/home/jan/flypulator_ws/src/flypulator/flypulator_gazebo_plugin/src/control_plugin.cc:799:9: error: ‘flypulator_common_msgs’ has not been declared
         flypulator_common_msgs::Vector6dMsg _rotor_cmd;
         ^
/home/jan/flypulator_ws/src/flypulator/flypulator_gazebo_plugin/src/control_plugin.cc:806:9: error: ‘_rotor_cmd’ was not declared in this scope
         _rotor_cmd.x1 = vel_1 * di_vel1;

**Comment by chaolmu** [comment]
I think the reason is that the include <flypulator_common_msgs/*.h> can not be found at that moment, since flypulator_commen_msgs is not compiled. That's why second run succeeded.

**Comment by chaolmu** [comment]
googled a solution: https://answers.ros.org/question/62092/catkin_make-started-failing-to-generate-h-from-msg/
to ensure things always get built in the correct order:
 add_dependencies(your_program ${catkin_EXPORTED_TARGETS})
