### ISSUE TITLE
State Estimation Package

### ISSUE THREAD

**Issue by danneboom** [FLYing-maniPULATOR/flypulator#6]
Hi, 
I think we need a state estimation package as well, which performs in future the state estimation from IMU and Camera data. 
I suggest we write a small package which takes as input the true pose from gazebo, adds noise and outputs state messages to the controller. Do you agree?

I also could watch the true pose in controller package itself, but in this case the package would have to be changed again when the real state estimation is available, so I would suggest the solution with a small state estimation "simulation" package.

**Comment by chaolmu** [comment]
Indeed. We simulate the State estimation with artifical errors, updaterate and latency.  This package belongs to simulation stack. while the real state estimation is for hardware.

**Comment by danneboom** [comment]
Do you mean a gazebo plugin? 
Who should implement this? me or Jinyao?

**Comment by chaolmu** [comment]
add this function to where the joint_state is published in gazebo plugin or implement it as a separate ros node, make a decision which is easier for you and implemnt it by yourself if you are already at this stop. Otherwise Jinyao will do it later. It depends on the urgency. Pls give a feedback.

**Comment by danneboom** [comment]
Probably its the best to write a gazebo plugin which suscribes to the gazebo state nodes and publishes MultiDOFJointState messages. 

@JinyaoZhu would it be okay if you set up a new gazebo plugin (state_estimation.cpp inside *flypulator_gazebo_plugin*) and you add the suscriber part since you surely now better which gazebo nodes are the correct nodes to get the UAVs pose, velocity and acceleration? I would implement the publishing part as well as the sensor noise in the following.
Its enough if it is done during the next week. But if you are busy, please tell me and I will try to set up the plugin by myself.

**Comment by JinyaoZhu** [comment]
@danneboom Yes, we have holiday, I think I can get it done next week.

**Comment by danneboom** [comment]
MultiDOFJointState message is not suitable, we need the same content as the trajectory message. So I would suggest message type MultiDOFJointTrajectoryPoint or own message type with same content.

**Comment by chaolmu** [comment]
Yes, we need to keep desired value and feedback value as same type. MultiDOFJointTrajectoryPoint and MultiDOFJointTrajectory are good choices for trajectory and desired pose, but "trajectory" sound bit wired for state estimation. What do you think, should we define a own type with proper name e.g. MultiDOFJointState with the same content?

**Comment by chaolmu** [comment]
@JinyaoZhu you update the state publication in subscriber of  gazebo link states. In this way the state estimation should be synchronized with gazebo/link_states. Is there any other reason? Is the update rate of link_states configurable or it is fixed with gazebo? The disadvantage is that gazebo node publish and subscribe the same topic (as the solution in aero_plugin). It is a urgly extern loop. The callback of gazebo update is an alternative with the cost of losing sychronized feature. However the publish rate of estimation is fixed, which makes the synchronization whatever impossible.

**Comment by danneboom** [comment]
@chaolmu Yes I think we should define a own type with proper name and same content. "UAVState" is a good naming in my opinion.
