### ISSUE TITLE
Gazebo error

### ISSUE THREAD

**Issue by chaolmu** [FLYing-maniPULATOR/flypulator#8]
After integration of the new urdf model, I have changed the joint name in aero and control plugins. Gazebo crashed after loading plaugins. It seems the joint  or lin name somewhere is not proper. But I can not locate it.

SpawnModel script started
[INFO] [1526999525.087478, 0.000000]: Loading model XML from file
[INFO] [1526999525.088034, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
[INFO] [1526999525.391311, 0.000000]: Calling service /gazebo/spawn_urdf_model
[ INFO] [1526999525.411648548, 0.028000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[INFO] [1526999525.722589, 0.157000]: Spawn status: SpawnModel: Successfully spawned entity
[ INFO] [1526999525.743630020, 0.157000000]: Physics dynamic reconfigure ready.
[ INFO] [1526999525.959067794, 0.157000000]: Loading AeroPlugin ...
[ INFO] [1526999525.959234677, 0.157000000]: aero_plugin get node:/gazebo_client
[ INFO] [1526999525.988696647, 0.157000000]: AeroPlugin Loaded !
[ INFO] [1526999526.013836245, 0.157000000]: control_plugin get node:/gazebo_control
[ INFO] [1526999526.056698855, 0.157000000]: ControlPlugin Loaded !
[ INFO] [1526999526.059528631, 0.157000000]: Loading FakeSensorPlugin ...
[ INFO] [1526999526.059619994, 0.157000000]: fake_sensor_plugin get node:/gazebo_client
[ INFO] [1526999526.068373903, 0.157000000]: FakeSensorPlugin Loaded !
gzserver: /usr/include/boost/smart_ptr/shared_ptr.hpp:648: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = gazebo::physics::Link; typename boost::detail::sp_member_access<T>::type = gazebo::physics::Link*]: Assertion `px != 0' failed.

Any ideas?

**Comment by chaolmu** [comment]
the model can be spowned successfully without gazebo plugins, I will check which plugin is the error in.

**Comment by JinyaoZhu** [comment]
@chaolmu the error is caused by the error blade_link name, I have updated the aero_plugin.
